name: "optimize"
version: "2.0.1"
usage: "optimize resource spec of running containers during an install or upgrade"
description: |-
  Inject Densify insights (if available) into the resource specificiations of your running containers 
  whenever install or upgrade is called.  Insights are extracted from your preferred parameter repository 
  (AWS Parameter Store, Densify).

  SYNOPSIS
    helm optimize [OPTION]
    helm optimize [HELM COMMAND]

  OPTIONS:
    -c, --configure
      use this command to invoke a wizard to configure the parameter repo adapter.
    
    -h, --help, help
      use this to get more information about the optimize plugin for helm

  OPTIMIZATION
    Simply use helm as you normally would, but add the 'optimize' keyword before any command.
    The plugin will lookup the optimal resource spec from the configured repository.
    
    Eg: helm optimize (install/upgrade) chart chart_dir/ --values value-file1.yaml -f value-file2.yaml

ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/helm-optimize-resources"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh"
